[package]
name = "partitioned-smc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aig = { path = "../aig-rs" }
# biodivine-lib-bdd = { path = "../biodivine-lib-bdd" }
cudd = { path = "../cudd-rs" }
